name: Issue Management

on:
  issues:
    types: [opened]

jobs:
  issue-opened:
    name: Issue Opened
    runs-on: ubuntu-latest
    steps:
      - name: Label needs triage
        uses: Naturalclar/issue-action@v1.0.0
        with:
          keywords: '[""]'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          labels: '["help wanted"]'
      - name: Create comment
        uses: actions/github-script@0.9.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '👋 Thanks for reporting!'
            })