name: Issue Management

on:
  issues:
    types: [opened]

jobs:
  issue-opened:
    name: Issue Opened
    runs-on: ubuntu-latest
    steps:
      - name: Label needs triage
        uses: Naturalclar/issue-action@v1.0.0
        with:
          keywords: '[""]'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          labels: '["help wanted"]'
      - name: Create comment
        uses: jungwinter/comment@v1
        id: create
        with:
          type: create
          body: "Thanks. We will review it as soon as possible."
          token: ${{ secrets.GITHUB_TOKEN }}